### ISSUE TITLE
Populate readme

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis#8]
This repo has a blank readme right now. The readme is also shown on https://packagist.org/packages/altis/altis so it would be good to get some stuff added!

**Comment by roborourke** [comment]
We need to decide what stuff! Thinking:

- [ ] Brief intro text eg. the short "What is Altis DXP?"
- [ ] Quick start guide with composer create-project command and composer command to start local server
- [ ] Links to: 
  - Altis website docs
  - Altis product tour

**Comment by joehoyle** [comment]
Another option could be to mostly mirror the content from https://www.altis-dxp.com/resources/docs/

**Comment by roborourke** [comment]
Fixed by @jazzsequence in #10 - cheers Chris!
